---
- name: configure httpd
  copy: 
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
  notify:
    - restart apache

- name: make a html file
  copy:
    src:  index.html
    dest: /var/www/html/index.html
